module.exports = {
    cascader: require('./cascader'),
    checkBox: require('./checkBox'),
    datePicker: require('./datePicker'),
    input: require('./input'),
    dynamicList: require('./dynamicList'),
    editor: require('./editor'),
    inputNumber: require('./inputNumber'),
    inputTimeSelect: require('./inputTimeSelect'),
    mapSelect: require('./mapSelect'),
    radio: require('./Radio'),
    rangePicker: require('./rangePicker'),
    select: require('./select'),
    selectMultiple: require('./selectMultiple'),
    selectMultiplePlate: require('./selectMultiplePlate'),
    selectMultipleTable: require('./selectMultipleTable'),
    selectSingleTree: require('./selectSingleTree'),
    tableTitle: require('./tableTitle'),
    textArea: require('./textArea'),
    timePicker: require('./timePicker'),
    twoInput: require('./twoInput'),
    upload: require('./upload'),
    uploadImage: require('./uploadImage'),
    version: '1.0.0'
  };